window:
  decorations: None

font:
  normal:
      family: SauceCodePro Nerd Font
      style: Regular
  bold:
      family: SauceCodePro Nerd Font
      style: Bold
  italic:
      family: SauceCodePro Nerd Font
      style: Italic
  size: 24.0

shell:
  program: /bin/bash
  args:
    - -cl
    - exec tmux new-session -As main

