os:
  editPreset: 'nvim'

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
gui:
  # use the mocha catppuccin theme
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red

customCommands:
  - key: '<C-p>'
    description: 'Use Git Genie to create a commit'
    context: 'files'
    command: 'ai_commit'
    loadingText: 'Creating commit...'
