os:
  editPreset: 'nvim'

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
gui:
  # use the mocha catppuccin theme
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red


  # - key: "<C-p>"
  #   command: "gh pr create --fill --web"
  #   context: "global"
  #   loadingText: "Creating pull request on GitHub"
# customCommands:
#   - key: "<C-p>"
#     command: 'export OPENAI_API_KEY=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  &&  git gci -n 5 -f'
#     context: "global"
#     loadingText: "Generating commit messages"
      #
customCommands:
  - key: '<C-p>'
    description: 'Use Git Genie to create a commit'
    context: 'files'
    prompts:
      - type: 'menuFromCommand'
        title: 'Select a commit message'
        key: 'Message'
        command: 'git gci -n 5 -f'
        loadingText: 'Loading commit messages...'
    command: 'git commit -m "{{index .PromptResponses 0}}"'
    loadingText: 'Creating commit...'
